version: '2'
services:
  seed:
    build: seed
    ports:
      - "2552:2552"
    environment:
      CLUSTER_IP: 192.168.99.100
      APP_PORT: 2552
      BIND_HOSTNAME: 0.0.0.0
      #SEED_PORT_1600_TCP_ADDR: seed

  frontend:
    build: frontend
    ports:
      - '8080:8080'
      - '2553:2553'
    environment:
      CLUSTER_IP: 192.168.99.100
      APP_PORT: 2553
      BIND_HOSTNAME: 0.0.0.0
      #SEED_PORT_1600_TCP_ADDR: seed

  backend:
    build: backend
    ports:
      - '2554:2554'
    environment:
      CLUSTER_IP: 192.168.99.100
      APP_PORT: 2554
      BIND_HOSTNAME: 0.0.0.0
      #SEED_PORT_1600_TCP_ADDR: seed