version: '2'
services:
  seed:
    build: seed
    ports:
      - '2552:2552'
    environment:
      CLUSTER_IP: seed
      APP_PORT: 2552
      BIND_HOSTNAME: 0.0.0.0
      SEED_PORT_1600_TCP_ADDR: seed

  frontend:
    build: frontend
    ports:
      - '8080:8080'
    environment:
      CLUSTER_IP: ""
      BIND_HOSTNAME: 0.0.0.0
      SEED_PORT_1600_TCP_ADDR: seed

  backend:
    build: backend
    environment:
      CLUSTER_IP: ""
      BIND_HOSTNAME: 0.0.0.0
      SEED_PORT_1600_TCP_ADDR: seed